language: python
dist: xenial
python:
  - "3.6"
install: "pip install -r requirements.txt"
script: "./manage.py test"
services:
  - postgresql
before_script:
  - psql -c 'create database keadatabase_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
  - cd src
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
branches:
  only:
  - master
