version: '3'

services:
  db:
    image: mdillon/postgis
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
        DATABASE_URL: postgis://postgres:postgres@db:5432/postgres
